##This file contains strings that have to be detected by django-admin.py
##makemessages

## standard log messages
_("Time is over. Forcing new phase")
_("Starting phase: %(phase)s")
_("Starting season: %(season)s")
_("Support from %(unit)s in %(area)s is broken")
_("%(unit)s in %(area)s converts into %(type)s")
_("A standoff occurs in %(area)s")
_("%(unit)s in %(origin)s invades %(area)s")
_("%(unit)s in %(area)s must retreat")
_("%(unit)s in %(area)s surrenders")
_("%(unit)s in %(area)s is now besieging")
_("%(unit)s in %(area)s is disbanded")
_("%(unit)s in %(origin)s retreats to %(area)s")
_("%(country)s gets control of %(area)s")
_("A new %(unit)s is placed in %(area)s")
_("%(country)s's order: %(order)s")

## country names
_("Austria")
_("Florence")
_("France")
_("Milan")
_("Naples")
_("Papacy")
_("Turks")
_("Venice")

## scenario names
_("Development")
_("The Spanish Preponderance")

## area names (excluding the areas whose name is the one of a country)
_("Albania")
_("Ancona")
_("Aquila")
_("Arezzo")
_("Avignon")
_("Bari")
_("Bergamo")
_("Bologna")
_("Bosnia")
_("Capua")
_("Carniola")
_("Carinthia")
_("Central Mediterranean")
_("Como")
_("Corsica")
_("Cremona")
_("Croatia")
_("Dalmatia")
_("Durazzo")
_("Ferrara")
_("Fornovo")
_("Friuli")
_("Genoa")
_("Gulf of Lions")
_("Gulf of Naples")
_("Herzegovina")
_("Hungary")
_("Ionian Sea")
_("Istria")
_("Lower Adriatic")
_("Ligurian Sea")
_("Lucca")
_("Mantua")
_("Marseille")
_("Messina")
_("Modena")
_("Montferrat")
_("Otranto")
_("Padua")
_("Palermo")
_("Parma")
_("Patrimony")
_("Pavia")
_("Perugia")
_("Piombino")
_("Pistoia")
_("Pisa")
_("Provence")
_("Ragusa")
_("Rome")
_("Salerno")
_("Saluzzo")
_("Sardinia")
_("Savoy")
_("Siena")
_("Slavonia")
_("Spoleto")
_("Swiss")
_("Treviso")
_("Trent")
_("Thyrrenian Sea")
_("Tunis")
_("Turin")
_("Tyrol")
_("Upper Adriatic")
_("Urbino")
_("Venice")
_("Verona")
_("Western Mediterranean")


## subject of the signup code email
_("Create an acccount on %(domain)s")
